# Generated by Django 4.2 on 2023-04-21 18:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 21, 18, 49, 34, 976184), verbose_name='Fecha de publicación'),
        ),
    ]
